// "use client"
import type { Metadata } from "next";
import "./globals.scss";
import { RecoilRoot } from "recoil";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <RecoilRoot>
    
    <html lang="en">
      <body>
          {children}
      </body>
    </html>
    // </RecoilRoot>
  );
}
